import { Product } from '@qatar-erp/types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    sku: 'MILK-ALM-1L',
    barcode: '6281007001015',
    name: 'Almarai Fresh Milk Full Cream 1L',
    nameAr: 'حليب المراعي طازج كامل الدسم 1 ليتر',
    localDescription: 'حليب المراعي طازج كامل الدسم 1 ليتر',
    shortDescription: 'Almarai Milk 1L',
    description: 'Fresh cow milk rich in calcium and vitamin D.',
    additionalDescription: 'Keep refrigerated below 4C.',
    categoryId: 'cat-dairy',
    categoryName: 'Dairy & Eggs',
    subDepartment: 'Fresh Dairy Counter',
    brandId: 'brand-almarai',
    brandName: 'Almarai',
    defaultVendor: 'Almarai Food Qatar W.L.L',
    
    // Costing & Taxes
    costPrice: 5.50,
    costInclTax: 5.50,
    landedCost: 5.60,
    costingMethod: 'Weighted Average',
    avgCost: 5.50,
    lastSupplierCost: 5.50,
    vatRate: 0.00,
    saleTaxRate: 0.00,
    purchaseTaxRate: 0.00,

    // Pricing & Margins
    retailPrice: 7.50,
    discount: 0.00,
    markupPercent: 36.36,
    grossProfitPercent: 26.67,
    priceInclTax: 7.50,
    msp: 7.00,
    wasPrice: 8.50,
    openPrice: false,

    wsPrice: 6.80,
    wsMarkupPercent: 23.64,
    wsGrossProfitPercent: 19.12,
    wsPriceInclTax: 6.80,
    wsMsp: 6.50,

    expDays: 14,
    weighingProductType: 'None',
    nonInventory: false,
    autoProductionWhileSale: false,
    procurementType: 'Normal Purchase',
    divisionFactor: 1.000,
    maxDiscountRate: 10.00,

    packings: [
      {
        id: 'pack-1',
        barcode: '6281007001015-CRTN',
        unit: 'Carton (12 Pcs)',
        packQty: 12,
        cost: 63.00,
        price: 84.00,
        priceInclTax: 84.00,
        productName: 'Almarai Milk 1L Box of 12',
        wasPrice: 90.00,
        wsPrice: 78.00,
        isStockUnit: false,
      },
    ],

    stockQuantity: 142,
    minStockLevel: 20,
    unit: 'Pcs',
    isActive: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'prod-002',
    sku: 'RICE-KAH-5KG',
    barcode: '8901234567890',
    name: 'Khabari Basmati Rice 5kg',
    nameAr: 'أرز خاري بسمتي 5 كجم',
    localDescription: 'أرز خاري بسمتي 5 كجم ممتاز',
    shortDescription: 'Khabari Rice 5kg',
    description: 'Long grain aromatic traditional basmati rice.',
    categoryId: 'cat-rice',
    categoryName: 'Rice & Grains',
    subDepartment: 'Grains & Staples',
    brandId: 'brand-khabari',
    brandName: 'Khabari',
    defaultVendor: 'Doha Wholesale Trading W.L.L',

    costPrice: 32.00,
    costInclTax: 32.00,
    landedCost: 33.50,
    costingMethod: 'FIFO',
    avgCost: 32.00,
    lastSupplierCost: 32.00,
    vatRate: 0.00,

    retailPrice: 45.00,
    discount: 0.00,
    markupPercent: 40.63,
    grossProfitPercent: 28.89,
    priceInclTax: 45.00,
    msp: 42.00,
    wasPrice: 49.00,

    wsPrice: 39.00,
    wsMarkupPercent: 21.88,
    wsGrossProfitPercent: 17.95,
    wsPriceInclTax: 39.00,

    expDays: 365,
    weighingProductType: 'None',
    procurementType: 'Normal Purchase',

    stockQuantity: 58,
    minStockLevel: 10,
    unit: 'Pcs',
    isActive: true,
    createdAt: '2026-01-12T09:30:00Z',
    updatedAt: '2026-08-05T14:20:00Z',
  },
  {
    id: 'prod-003',
    sku: 'WAT-RAY-500ML',
    barcode: '6251034000012',
    name: 'Rayyan Natural Water 500ml (Pack of 24)',
    nameAr: 'مياه الريان الطبيعية 500 مل (كرتون 24)',
    localDescription: 'مياه الريان الطبيعية 500 مل (كرتون 24)',
    shortDescription: 'Rayyan Water 24x500ml',
    categoryId: 'cat-beverages',
    categoryName: 'Beverages',
    subDepartment: 'Water & Juices',
    brandId: 'brand-rayyan',
    brandName: 'Rayyan',
    defaultVendor: 'Rayyan Water Company W.L.L',

    costPrice: 12.00,
    costInclTax: 12.00,
    landedCost: 12.00,
    avgCost: 12.00,
    lastSupplierCost: 12.00,
    vatRate: 0.00,

    retailPrice: 18.00,
    discount: 0.00,
    markupPercent: 50.00,
    grossProfitPercent: 33.33,
    priceInclTax: 18.00,
    msp: 16.00,
    wasPrice: 20.00,

    wsPrice: 15.00,
    expDays: 365,

    stockQuantity: 210,
    minStockLevel: 30,
    unit: 'Box',
    isActive: true,
    createdAt: '2026-02-01T11:00:00Z',
    updatedAt: '2026-08-10T12:00:00Z',
  },
];
